apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-pipeline
description: Hello World pipeline with dev and prod on GKE
serialPipeline:
  stages:
    - targetId: hello-pipeline-target-1
      profiles: ["dev"]
    - targetId: hello-pipeline-target-2
      profiles: ["prod"]
      strategy:
        standard:
          approvalRequired: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: hello-pipeline-target-1
description: Dev environment GKE
gke:
  cluster: projects/trial-003-457615/locations/us-central1/clusters/gke-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: hello-pipeline-target-2
description: Prod environment GKE
gke:
  cluster: projects/trial-003-457615/locations/us-central1/clusters/gke-prod
# apiVersion: deploy.cloud.google.com/v1
# kind: DeliveryPipeline
# metadata:
#   name: hello-pipeline
# description: Hello World pipeline with dev and prod on GKE
# serialPipeline:
#   stages:
#     - targetId: dev
#       profiles: []
#     - targetId: prod
#       profiles: []
#       strategy:
#         standard:
#           approvalRequired: true
# ---

# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: dev
# description: Dev environment GKE
# gke:
#   cluster: projects/trial-003-457615/locations/us-central1/clusters/gke-dev
# ---

# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: prod
# description: Prod environment GKE
# gke:
#   cluster: projects/trial-003-457615/locations/us-central1/clusters/gke-prod
