apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: hello-world

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/trial-003-457615/hello-repo/hello-image

deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml

profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - k8s/dev/*.yaml

  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/prod/*.yaml

































# apiVersion: skaffold/v2beta29
# kind: Config
# metadata:
#   name: hello-world

# build:
#   artifacts:
#     - image: us-central1-docker.pkg.dev/trial-003-457615/hello-repo/hello-image

# deploy:
#   kubectl:
#     manifests:
#       - k8s/deployment.yaml
#       - k8s/service.yaml

# profiles:
#   - name: dev
#     deploy:
#       kubectl:
#         manifests:
#           - k8s/dev/*.yaml

#   - name: prod
#     deploy:
#       kubectl:
#         manifests:
#           - k8s/prod/*.yaml
